from django.urls import path

from . import views

urlpatterns = [
    path('public/home', views.home_view),
    path('public/contact', views.contact_view),
    path('public/profiles/<str:public_id>', views.public_profile_view),
    path('public/profiles/<str:public_id>/reviews', views.public_profile_reviews_view),
    path('auth/register', views.register_view),
    path('auth/login', views.login_view),
    path('auth/logout', views.logout_view),
    path('auth/forgot-password', views.forgot_password_view),
    path('auth/verify-email', views.verify_email_view),
    path('me', views.me_view),
    path('account/profile', views.profile_view),
    path('account/security', views.security_view),
    path('account/password', views.password_view),
    path('catalog/filters', views.catalog_filters_view),
    path('listings', views.listings_view),
    path('listings/<str:public_id>', views.listing_detail_view),
    path('buyer/dashboard', views.buyer_dashboard_view),
    path('buyer/saved-vehicles', views.saved_vehicles_view),
    path('buyer/saved-vehicles/<str:public_id>', views.saved_vehicle_detail_view),
    path('buyer/search-history', views.search_history_view),
    path('buyer/search-history/<str:public_id>', views.search_history_detail_view),
    path('appointments/calendar', views.appointments_calendar_view),
    path('appointments/slots', views.appointment_slots_view),
    path('appointments', views.appointments_view),
    path('appointments/<str:public_id>', views.appointment_detail_view),
    path('appointments/<str:public_id>/confirm', views.appointment_confirm_view),
    path('appointments/<str:public_id>/reschedule', views.appointment_reschedule_view),
    path('appointments/<str:public_id>/cancel', views.appointment_cancel_view),
    path('seller/dashboard', views.seller_dashboard_view),
    path('seller/listings', views.seller_listings_view),
    path('seller/listings/form-options', views.seller_listing_form_options_view),
    path('seller/listings/<str:public_id>', views.seller_listing_detail_view),
    path('lessor/rentals', views.lessor_rentals_view),
    path('lessor/rentals/<str:public_id>', views.lessor_rental_detail_view),
    path('lessor/rentals/<str:public_id>/close', views.lessor_rental_close_view),
    path('admin/dashboard', views.admin_dashboard_view),
    path('admin/users', views.admin_users_view),
    path('admin/users/<str:public_id>', views.admin_user_detail_view),
    path('admin/users/<str:public_id>/status', views.admin_user_status_view),
    path('admin/listings', views.admin_listings_view),
    path('admin/listings/<str:public_id>', views.admin_listing_detail_view),
    path('admin/listings/<str:public_id>/review', views.admin_listing_review_view),
    path('admin/appointments', views.admin_appointments_view),
    path('admin/appointments/<str:public_id>', views.admin_appointment_detail_view),
    path('admin/catalog', views.admin_catalog_view),
    path('admin/catalog/collections', views.admin_catalog_collections_view),
    path('admin/catalog/<str:kind>', views.admin_catalog_item_view),
    path('admin/catalog/<str:kind>/<str:public_id>', views.admin_catalog_item_detail_view),
    path('admin/moderation', views.admin_moderation_view),
    path('admin/moderation/listings', views.admin_moderation_listings_view),
    path('admin/moderation/listings/<str:public_id>/approve', views.admin_moderation_approve_view),
    path('admin/moderation/listings/<str:public_id>/reject', views.admin_moderation_reject_view),
    path('admin/moderation/listings/<str:public_id>', views.admin_moderation_delete_view),
    path('admin/reports', views.admin_reports_view),
    path('admin/reports/<str:public_id>/start-review', views.admin_report_start_view),
    path('admin/reports/<str:public_id>/resolve', views.admin_report_resolve_view),
    path('admin/reports/<str:public_id>', views.admin_report_detail_view),
    path('admin/suspensions', views.admin_suspensions_view),
    path('admin/suspensions/form-options', views.admin_suspension_form_options_view),
    path('admin/suspensions/save', views.admin_suspension_save_view),
    path('admin/suspensions/<str:public_id>/reinstate', views.admin_suspension_reinstate_view),
    path('admin/suspensions/<str:public_id>', views.admin_suspension_detail_view),
]
