# Generated by Django 6.0.4 on 2026-04-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='AdminSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('brands', 'brands'), ('models', 'models'), ('vehicle-types', 'vehicle-types'), ('locations', 'locations')], max_length=32)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('mode', models.CharField(default='sale', max_length=16)),
                ('status', models.CharField(default='published', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('transmission', models.CharField(blank=True, max_length=128)),
                ('fuel', models.CharField(blank=True, max_length=128)),
                ('mileage_km', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('city_id', models.CharField(blank=True, max_length=64)),
                ('city_name', models.CharField(blank=True, max_length=128)),
                ('state_name', models.CharField(blank=True, max_length=128)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='listings/cover/')),
                ('cover_image_external_url', models.URLField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('price_per_day', models.IntegerField(blank=True, null=True)),
                ('price_per_week', models.IntegerField(blank=True, null=True)),
                ('price_per_month', models.IntegerField(blank=True, null=True)),
                ('deposit_amount', models.IntegerField(blank=True, null=True)),
                ('km_included_per_day', models.IntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('vin_masked', models.CharField(blank=True, max_length=64)),
                ('doors', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=64)),
                ('traction', models.CharField(blank=True, max_length=64)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('gallery_urls', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('seller_profile_extra', models.JSONField(blank=True, default=dict)),
                ('views', models.IntegerField(default=0)),
                ('messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('appointment_type', models.CharField(default='test-drive', max_length=64)),
                ('buyer_name', models.CharField(blank=True, max_length=128)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=64)),
                ('seller_name', models.CharField(blank=True, max_length=128)),
                ('seller_email', models.EmailField(blank=True, max_length=254)),
                ('seller_phone', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_appointments', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_appointments', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='autosphere_api.listing')),
            ],
            options={
                'ordering': ['date', 'time', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='autosphere_api.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('avatar_preset', models.CharField(default='aurora', max_length=32)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('primary_surface', models.CharField(default='buyer', max_length=32)),
                ('support_message', models.TextField(blank=True, default='Mantén este correo actualizado para recuperar acceso y recibir avisos importantes de la cuenta.')),
                ('password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('author_name', models.CharField(max_length=128)),
                ('author_role', models.CharField(blank=True, max_length=64)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('created_at', models.DateField()),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('query', models.CharField(max_length=255)),
                ('result_count', models.IntegerField(default=0)),
                ('filters_summary', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='SavedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='autosphere_api.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
